[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/products"
  to = "/.netlify/functions/products"
  status = 200

[[redirects]]
  from = "/api/product-image"
  to = "/.netlify/functions/product-image"
  status = 200
